name: Docker Image Notifications Service
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  jwt_secret: ${{ secrets.JWT_SECRET }}

jobs:
  publish-docker-image:
    strategy:
        matrix:
          jdk: [17]
          os: [ubuntu-18.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3

    - name: Set up JDK 173
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Notifications Service with Maven
      run: |
        cd notifications
        mvn -B package
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta-notifications
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}/notifications

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: notifications/.
        file: notifications/Dockerfile
        push: true
        tags: ${{ steps.meta-notifications.outputs.tags }}
        labels: ${{ steps.meta-notifications.outputs.labels }}
