name: Hello world Self-Hosted
on: workflow_dispatch

jobs:
  hello-world-job:
    runs-on: [self-hosted, Linux, x64]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run a one-line script
      run: echo 'Hello World'
