name: Java CI with Maven With Secret
on: workflow_dispatch
  
jobs:
  build-auth-service:
  
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 173
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      env:
        jwt_secret: ${{ secrets.JWT_SECRET }}
        
    - name: Build Auth Service with Maven
      run: |
        cd authusers
        mvn -B package
        
  build-notifications-service:
  
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 173
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      env:
        jwt_secret: ${{ secrets.JWT_SECRET }}
        
    - name: Build Notifications Service with Maven
      run: |
        cd notifications
        mvn -B package
  
  build-todo-service:
  
    strategy:
      matrix:
        jdk: [17]
        os: [ubuntu-18.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 173
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      env:
        jwt_secret: ${{ secrets.JWT_SECRET }}
        
    - name: Build ToDo Service with Maven
      run: |
        cd todolist
        mvn -B package
